# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc4c715b199edc8a0850c7cea8026c70b2784cc9c1e47acab85b6663258503ba8c64fb71413a6043bd9a065810511207729ce364e696687c6a5ba682baba1e1

test:
  secret_key_base: 9c38f28952fa910b67e6da287ed1792f65116add377989cfc2b69a7264ad4685bddf0bc158b3984a8914b5dbbbb2dfe388f70c196d28154314e60e83ab8ae64e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
